[package]
name = "driver_test"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
thirtyfour = { version = "0.35.0"}
tokio = { version = "1.44.2", features = ["full"] }
